# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8b652a70991f81c511b137369e345e796bf99c487b59380ec7f8493431b1bc4ea04eb5ed165d309ed25c533dc12deb5d16b1e3397776506d7d0be8a04616cf3

test:
  secret_key_base: a944ce076823536cee6b02e702657c856723d8662026d5d8fbc748bc68929169382de404d357742b1dee80d05d56b291a173a24c43f8b92922d453d32567c1fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
